name: ligo
dependencies:
  - python=3.9
  - pip
  - pip:
      - numpy
      - matplotlib
      - scipy
      - h5py
      - ipython
      - jupyter
      - requests
      - astropy
      - ipykernel=6.29
